language: android
jdk: oraclejdk7

env:
  matrix:
    - ANDROID_SDKS=android-19  ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-19.1.0
  licenses:
    - android-sdk-license-5be876d5

before_install: 
  - git submodule update --init --recursive
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

#script:
#  - ./gradlew build

before_script:
  - chmod +x ./ci/wait_for_emulator
  - ./ci/wait_for_emulator
  - adb shell input keyevent 82 &
