language: android
jdk: oraclejdk8

env:
  matrix:
    - ANDROID_SDKS=android-19  ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-19.1.0
  licenses:
    - android-sdk-license-5be876d5

before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

install:
  - npm install -g mountebank --production

before_script:
  - mb &
  - chmod +x ./ci/wait_for_emulator
  - ./ci/wait_for_emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedCheck
