language: android
jdk: oraclejdk7
before_install: 
  - git submodule update --init
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
env:
  matrix:
    - ANDROID_SDKS=android-19,sysimg-19  ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
before_script:
  - wait_for_emulator


android:
  components:
    - build-tools-19.0.2
    - android-19
