language: android
jdk: oraclejdk8

env:
  matrix:
    - ANDROID_SDKS=android-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a ANDROID_TRAVIS=1

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-24
    - extra-android-support
    - extra-google-m2repository
    - extra-google-google_play_services
    - extra-android-m2repository

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - chmod +x ./ci/wait_for_emulator
  - ./ci/wait_for_emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew createDebugCoverageReport coveralls
