sudo: required
language: android
jdk: oraclejdk8

env:
  global:
    - EMULATOR_API=22
    - ANDROID_API=28
    - ANDROID_BUILD_TOOLS=28.0.3
    - ANDROID_TRAVIS=1
    - secure: iXVs65+lPjyTr60MsX9K2WpjJ5ijt4cnBE9PT6ouHSjkZjugotaNoX3nXZev8fKFLsH0JPxpsxBVy66jz6iOddMfLdzSiL2oOeeYNxyNThOdGp9R/JmYtivgrMm6v3e1zzCLvj9onOwBUVdWVLD/BXgYi7wP96rJFENlVjuszys=
    - secure: BXwZhWDFFXzdaTAPAvMKeOfnLHxkmdXoeMZ/GtVYkT62JxeuiaTW6Z6rT0gZKAEyxmUBxFX1CP+1m1Gi0cWrQHfTBbFDJO7iKu7mG9LcZhQ8Cm657yt2TBc+fnVqbG5OxXWhSBs1lF1gZJ6+ehEIJn3YjP6fDYv0fNnTGpYHCYo=

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API
    - extra-android-support
    - extra-google-m2repository
    - extra-google-google_play_services
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API # google play services
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API
    - sys-img-armeabi-v7a-android-$EMULATOR_API # the fix!
  
  licenses:
    - ".+"
  before_install:
    - yes | sdkmanager "platforms;android-28"

before_script:
  - echo "y" | android update sdk -a --no-ui --filter android-28
  - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-28
  - android list targets | grep -E '^id:' | awk -F '"' '{$1=""; print $2}' # list all targets
  - echo no | avdmanager create avd --force -n test -k "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  - emulator -avd test -no-audio -no-window -gpu swiftshader &
  - chmod +x ./ci/wait_for_emulator
  - ./ci/wait_for_emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew createDebugCoverageReport coveralls
  - ./gradlew snowplow-demo-app:assemble

deploy:
  skip_cleanup: true
  provider: script
  script: ./.travis/deploy.sh $TRAVIS_TAG
  on:
    tags: true
